services:
  - type: web
    name: nickel-inventory
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate --force
      php artisan migrate --force
      php artisan db:seed --force
      php artisan optimize
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr